### ISSUE TITLE
Optionally not creating child in ChildReconciler result in reconcile error

### ISSUE THREAD

**Issue by gmrodgers** [vmware-labs/reconciler-runtime#273]
From my understanding of the documentation, if I return `nil, nil` in a `ChildReconciler` the reconcile sequence should continue on without erroring:

But I see the following error returned:

```
<*errors.StatusError | 0xc00069efa0>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: " \"\" is invalid: metadata.name: Required value: name is required",
                Reason: "Invalid",
                Details: {
                    Name: "",
                    Group: "",
                    Kind: "",
                    UID: "",
                    Causes: [
                        {
                            Type: "FieldValueRequired",
                            Message: "Required value: name is required",
                            Field: "metadata.name",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 422,
            },
        }
```

And here is my `DesiredChild` field:

```go
DesiredChild: func(ctx context.Context, parent *rcv1alpha1.ResourceClaim) (*secretgen.SecretImport, error) {
			if parent.Spec.Ref.Namespace != parent.Namespace {
				return &secretgen.SecretImport{
					ObjectMeta: metav1.ObjectMeta{
						Labels:      make(map[string]string),
						Annotations: make(map[string]string),
						Name:        parent.Status.Binding.Name,
						Namespace:   parent.Namespace,
					},
					Spec: secretgen.SecretImportSpec{
						FromNamespace: parent.Spec.Ref.Namespace,
					},
				}, nil
			}

			return nil, nil
		},
}
```

I believe this may come from the use of reflection in the calling of `DesiredChild` and it casting a nil to the Child type and getting an empty child.

Or are there any extra steps I need to do to achieve this optional child creation?

Thanks!

**Comment by mamachanko** [comment]
> From my understanding of the documentation, if I return nil, nil in a ChildReconciler the reconcile sequence should continue on without erroring

I can confirm that. We are using a `ChildReconciler` for the management of an optional child resource. It only creates the child if required, i.e. `child != nil`, and deletes it if required.

Which version are you using, @gmrodgers?

**Comment by scothis** [comment]
Returning `nil` as the desired child resource is supported and should work. We have test cases that cover this case for when a child resource was previously defined and now should be removed, as well as for when there isn't a child resource (no-op).

If you are able, can you include the rest of the ChildReconciler as well as the content of the parent resource as it enters the ChildReconciler. I wonder if the parent resource doesn't define `parent.Status.Binding.Name`. This would led to the child's SecretImport being defined without a name.

**Comment by gmrodgers** [comment]
Ah yes you're spot on with this @scothis , managed to crack down the issue today.  Thanks @scothis and @mamachanko !
