### ISSUE TITLE
ChildReconciler supports the usecase where the name/namespace of the child changes between reconciles

### ISSUE THREAD

**Issue by gmrodgers** [vmware-labs/reconciler-runtime#302]
I have a usecase where I want to create a resource in one namespace and then, on the changing of a field in the spec, create a resource in a different namespace whilst cleaning up the old one.  The current implementation will assume that the resource is in the same namespace (obtaining it via OurChild and ListOptions) and then try to patch it but it will fail since it is a different resource!

The type of DesiredChild I'd like to have support for:

```
return &corev1.ConfigMap{
	ObjectMeta: metav1.ObjectMeta{
		Name:        parent.Spec.Ref.Name,
		Namespace:  parent.Spec.Ref.Namespace,
	},
}, nil
```

My current workaround is to use a `SyncReconciler` beforehand to delete the resource if it detects a change of name or namespace

**Comment by scothis** [comment]
There's no way in Kubernetes to update the namespace or name of a resource. You have to create a new resource and delete the old resource. Managing the semantics of the create/delete operations is up to you (delete then create, create then delete, create and wait for ready before delete, ...), using a SyncReconciler to managed the delete is correct.

Can you post the `OurChild` method for the reconciler? My guess is that the method isn't accounting for the namespace before returning a resource as matching. Once you need to manage the child resource in different namespace, any existing child should be abandoned and cleaned up via a separate process.

**Comment by gmrodgers** [comment]
I think the `ListOptions` is taking the namespace into account

```go
func ListOptions(ctx context.Context, parent *rcv1alpha1.ResourceClaim) []client.ListOption {
	var listOptions []client.ListOption
	hasPreviouslyClaimed := parent.Status.ClaimedResourceRef != nil
	if hasPreviouslyClaimed {
		listOptions = append(listOptions, client.InNamespace(parent.Status.ClaimedResourceRef.Namespace))
	}

	return listOptions
}

func OurChild(parent *rcv1alpha1.ResourceClaim, child *secretgen.SecretExport) bool {
	hasPreviouslyClaimed := parent.Status.Binding.Name != ""
	wasForClaimedSecret := hasPreviouslyClaimed && parent.Status.Binding.Name == child.Name

	return wasForClaimedSecret
}
```

**Comment by scothis** [comment]
This can be done with the new ChildSetReconciler (from #396) by switching the value returned from IdentifyChild when the name/namespace are updated. Depending on the lexical order of the returned IDs, there may be a window where both resources exist, or neither exists.
