### ISSUE TITLE
Call ReflectChildStatusOnParent when DesiredChild returns error

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [vmware-labs/reconciler-runtime#336]
Currently, `ReflectChildStatusOnParent(parent, nil, err)` will only be called if `apierrs.IsAlreadyExists`. Any other error will be returned to the controller-runtime to requeue without invoking `ReflectChildStatusOnParent`:
https://github.com/vmware-labs/reconciler-runtime/blob/398e82056df0ab5aa1f0d3beb86a71d77f597fdf/reconcilers/reconcilers.go#L1073
https://github.com/vmware-labs/reconciler-runtime/blob/398e82056df0ab5aa1f0d3beb86a71d77f597fdf/reconcilers/reconcilers.go#L1288

If the status isn't updated, a user viewing the CR will see stale state, and would have to check controller logs to find the failure. 

A workaround is to call `parent.GetConditionSet().Manage(parent.Status)` inside of `DesiredChild`, but given the method signatures this feels like it would be a side effect.

**Comment by scothis** [comment]
The behavior is intentional and documented. It's often not desirable to reflect any old go err on to the resources status. The status should be updated when there is some action the owner needs to take, but avoid internal flapping. Errors in this context are true exceptions, where you want to try again and expect to get a different result. An "error" that you want to reflect to the status is a known condition and not an error. This is similar to HTTP 4xx and 5xx "errors" vs an i/o socket interrupt.

Can you explain a bit more about your use case?

**Comment by xtreme-conor-nosal** [comment]
>The status should be updated when there is some action the owner needs to take
When such a user-actionable error prevents creating a child, the API signatures lead me to believe I should be handling status updates inside of reflectChildStatusOnParent, but it seems that's currently not possible.

>An "error" that you want to reflect to the status is a known condition and not an error. This is similar to HTTP 4xx and 5xx "errors" vs an i/o socket interrupt.
Is it not still beneficial to the user to see in the status that all is not well, even if the failure might be transient? There may also be overlap between "exceptions" from the controller's POV and "actionable" from the user's POV (e.g. untrusted CA) - the status is the first most visible place to surface information to the user.

I did miss some of the discrepancy between the basic go pattern of `if err != nil return err` and the controller runtime behaviour of treating errors as a retry.  Given I have a user-actionable error in a ResourceReconciler, during or prior to successfully defining a desiredchild, is there a recommended pattern between:
1) update parent status within DesiredChild
2) try to catch such errors in a SyncReconciler before the ChildReconciler (and update resource status there)
or something else?

The current docs for DesiredChild could more explicitly address intended error flow and semantics.
The comments at https://github.com/vmware-labs/reconciler-runtime/blob/b201955224344f6e0e34591ac1b52b81170e9ebc/reconcilers/reconcilers.go#L1014 and https://github.com/vmware-labs/reconciler-runtime/blob/b201955224344f6e0e34591ac1b52b81170e9ebc/reconcilers/reconcilers.go#L1062

**Comment by scothis** [comment]
> Given I have a user-actionable error in a ResourceReconciler, during or prior to successfully defining a desiredchild, is there a recommended pattern between:
> 1. update parent status within DesiredChild
> 2. try to catch such errors in a SyncReconciler before the ChildReconciler (and update resource status there)
or something else?

Neither. When operating under a ResourceReconciler you should let it handle the status updates for the resource being reconciled. The next line of the doc for DesiredChild may be operative:
> To skip reconciliation of the child resource while still reflecting an existing child's status on the reconciled resource, return [OnlyReconcileChildStatus](https://github.com/vmware-labs/reconciler-runtime/blob/b201955224344f6e0e34591ac1b52b81170e9ebc/reconcilers/reconcilers.go#L1004) as an error.

Generally, you want to handle the error close to where it occurs. If the error was caused before the ChildReconciler, it should be handled before the ChildReconciler. The error handling capabilities of ChildReconciler are focused on errors produced by the ChildReconciler.

We can look at allowing users to opt-in to more types of errors that can be handled by ReflectChildStatusOnParent, but it will never be a, generic, full featured error handler.
