### ISSUE TITLE
Allow Requeu/RequeueAfter when returning HaltSubReconcilers

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [vmware-labs/reconciler-runtime#389]
### Is your feature request related to a problem? Please describe.

I have a sequence reconciler, where the first subreconciler is a SyncReconciler implementing SyncWithResult. I conditionally want to return `(Result{RequeueAfter: duration}, HaltSubReconcilers)` because this first subreconciler needs to wait for asynchronous work to finish, and the following subreconciler depends on that work. Exponential backoff by returning another error type would not be appropriate for the timing of the work being done.

Because HaltSubReconcilers is an error, it gets caught in error handling blocks like
```
result, err := r.Reconciler.Reconcile(...)
if err != nil {
  return Result{}, err
}
```
between SyncWithResult and the ResourceReconciler, so the RequeueAfter value is lost.

### Describe the solution you'd like

When a HaltSubReconciler error is returned, propagate the subreconciler's Result instead of a new empty Result
e.g. 
```
result, err := r.Reconciler.Reconcile(...)
if err != nil {
  return result, err
}
```

For SyncReconciler https://github.com/vmware-labs/reconciler-runtime/blob/main/reconcilers/reconcilers.go#L908
For Sequence https://github.com/vmware-labs/reconciler-runtime/blob/main/reconcilers/reconcilers.go#L1303

### Describe alternatives you've considered

Move the HaltSubReconcilers into a new SubReconcilerResult field (instead of directly using the controller-runtime Result) e.g.
```
type SubReconcilerResult struct {
  Result
  HaltSubReconcilers bool
}
```
so that Halt can be used unambiguously as a successful result instead of a suppressed error.

**Comment by scothis** [comment]
@xtreme-conor-nosal sounds good, would you like to author a PR?

**Comment by xtreme-conor-nosal** [comment]
Sure. Do you have a preference between the two approaches? I think the new result struct would be clearer, but removing the existing error type would make it a breaking change.

**Comment by scothis** [comment]
> Sure. Do you have a preference between the two approaches? I think the new result struct would be clearer, but removing the existing error type would make it a breaking change.

the desired solution:

>When a HaltSubReconciler error is returned, propagate the subreconciler's Result instead of a new empty Result
e.g.
>
>```
>result, err := r.Reconciler.Reconcile(...)
>if err != nil {
>  return result, err
>}
>```
