### ISSUE TITLE
Determinism of IdentifyChild is confusing

### ISSUE THREAD

**Issue by squeedee** [vmware-labs/reconciler-runtime#481]
### Describe the bug

* given a set of resources on cluster `oc`
* when I process the KnownChildren (which is `oc`) and produce desired children `dc` (one-to-one for this example)
* then my IdentifyChild should work regardless of on-cluster mutations during the reconcile.

Because the ResourceManager lists and filters the resources via the client again, at the point of `.Manage` - it loads a possibly mutated resource and uses that for that last `IdentifyChild`

This leads to surprising results, because I take the guidance in the docs:
> // Non-deterministic IDs will result in the rapid deletion and creation of child resources.

to mean deterministic for the data passed to this `reconcile`

We were able to find a more "stable" form of identity, however it took a long time to discover the issue because of our assumptions about the data passed into the reconcile.

**Comment by mamachanko** [comment]
> We were able to find a more "stable" form of identity

Can you describe what identity you started out with and what you settled on eventually? I reckon it would help to exemplify the issue.

**Comment by scothis** [comment]
> > // Non-deterministic IDs will result in the rapid deletion and creation of child resources.
>
> to mean deterministic for the data passed to this `reconcile`

Deterministic within the context of a single reconcile request, but it would be odd for the value to change between different reconcile requests.

`IdentifyChild` is called for every known and desired child during the reconcile. The result is used to determine if a desired child needs to be created because it doesn't exist, update an existing resource, or delete a no longer desired resource.

**Comment by squeedee** [comment]
To try and add clarity:

* knownChildren = ListChildren -> 
* DesiredChildren(ctx-with-known) -> desiredList
* for each desired { create ChildReconciler }
* Child.rm.Manage - lists children, filters, and it's a newer version than seen in "knownChildren" above.

**Comment by scothis** [comment]
> Child.rm.Manage - lists children, filters, and it's a newer version than seen in "knownChildren" above.

ahh. Ok, this issue something that bugged me about the initial implementation as it's a bit inefficient, but didn't think it would cause issues. We can update the Manager to accept a list of known children so it doesn't re-list children. The update will fail if the underlying resource was mutated, as usual.

**Comment by squeedee** [comment]
Yah we're already conditioned to look for RV changes, but this was a "trying to create but it's gone" because it was now being treated as a create. It took a _lot_ of tracer logs for us to work this out, because we were working on the false assumption that the "data in" didn't change for the duration of the core reconciler methods, namely "DesiredChildren" and "IdentifyChild"
