### ISSUE TITLE
Push super manager capabilities upstream

### ISSUE THREAD

**Issue by glyn** [vmware-labs/reconciler-runtime#72]
The super manager proposed in https://github.com/vmware-labs/reconciler-runtime/pull/67 should be pushed upstream, as per [this comment](https://github.com/vmware-labs/reconciler-runtime/pull/67#discussion_r556600448).

**Comment by scothis** [comment]
I don't mean that SuperManager itself should be upstreamed, but the capabilities that it provides could be folded into the upstream Manager.

**Comment by glyn** [comment]
We are revisiting the design and more substantial upstream changes may be necessary.

**Comment by glyn** [comment]
Re-opening while we reconsider PR 67.

**Comment by glyn** [comment]
Slack [thread](https://kubernetes.slack.com/archives/CAR30FCJZ/p1611672907143100?thread_ts=1608132732.265400&cid=CAR30FCJZ).
