### ISSUE TITLE
Variable number of child resources

### ISSUE THREAD

**Issue by gmrodgers** [vmware-labs/reconciler-runtime#75]
Hey folks,

We're having a play around with reconciler-runtime and were seeking to create a variable number n of child resources.  To do this we are using the `ChildReconciler` but we hit a roadblock when we try to implement `DesiredChild` as the return type is just a singular resource and not a list.  

Example usecase: given our parent resource, we want to create x service accounts specified, which were specified a list on our parent resource.

Any thoughts on how to get round this for now?

Thanks,
Glen and @harshac

**Comment by scothis** [comment]
The set of SubReconcilers included today are meant to pave cow paths by making common patterns easy to drop in, but are by no means exhaustive. The `SubReconciler` interface is intended to plug in custom behavior. Managing multiple children is an area we can look to provide better support, but shouldn't block you from providing your own behavior.

The `ChildReconciler` is focused on managing a single child resource. There are (at least) three primary semantic models for managing multiple children of the same kind:

1. distinct children
    Define a ChildReconciler for each child resource being managed. Individual children need to be qualified so they can be distinguished.
2. immutable revisions
    Stamp out a new, immutable child rather than mutate an existing child. Similar to the model between Deployment and ReplicaSet. Inactive children are garbage collected.
3. child sets (this is what I think you're asking for)
    A set of child resources that vary in number over time. A stable key links the desired state to a specific desired child. Children with new keys are created, matching key are updated and missing keys are removed.

The existing behavior and `1. distinct children` can be viewed a degenerate cases of `3. child sets`.

Defining the happy path semantics should be relatively straight forward. The complexity will come from reflecting the children's status and handling partial failure when an error occurs.

**Comment by gmrodgers** [comment]
Yep this makes sense, I think we can look into creating a `ChildSetReconciler` and possibly just calling out to the child reconcilers.  Thanks for the tip in the right direction!

**Comment by scothis** [comment]
Resolved with #396
